### ISSUE TITLE
Add 'ttl' mapping for FCM

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-push-server#115]
Currently, we use "validTo" only for APNS messages, we should consider adding it also to FCM.

- https://firebase.google.com/docs/cloud-messaging/concept-options#ttl
- https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1

**Comment by romanstrobl** [comment]
I assume the property is `validUntil`, not `validTo`.
