### ISSUE TITLE
swallowed cause exception

### ISSUE THREAD

**Issue by honzasmuk** [wultra/powerauth-push-server#168]
Similar to https://github.com/wultra/powerauth-restful-integration/issues/69 the cause exceptions are swallowed. If there are some networking issues (dns, ssl, ...), nothing appears in log.
https://github.com/wultra/powerauth-push-server/blob/b45f529bb9c0389c11063a0e780b6a20d5754855/powerauth-push-client/src/main/java/io/getlime/push/client/PushServerClient.java#L692

**Comment by petrdvorak** [comment]
Again, a valid report. We should add logging. In this case, I would also favor for adding the "cause" exception to the thrown exception (unlike in PA RESTful Integration where public endpoints are published, we do not need to hide the cause exception from other systems).
