### ISSUE TITLE
Make sure push token is unique for given activation ID

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-push-server#262]
Currently, it seems that both Apple and Google issue new push token despite the fact the old didn't expire yet. We don't know why this happens but we need to handle this better.

**Comment by radekfrolik** [comment]
"17-10-2019 11:00:31"	"pocet smazanych radku je: 7"
"17-10-2019 10:00:31"	"pocet smazanych radku je: 3"
"17-10-2019 09:00:31"	"pocet smazanych radku je: 5"
"17-10-2019 08:00:31"	"pocet smazanych radku je: 5"
"17-10-2019 07:00:31"	"pocet smazanych radku je: 1"
"17-10-2019 06:00:31"	"pocet smazanych radku je: 3"
"17-10-2019 05:00:31"	"pocet smazanych radku je: 0"
"17-10-2019 04:00:31"	"pocet smazanych radku je: 0"
"17-10-2019 03:00:31"	"pocet smazanych radku je: 0"
"17-10-2019 02:00:31"	"pocet smazanych radku je: 0"
"17-10-2019 01:00:30"	"pocet smazanych radku je: 1"
"17-10-2019 00:00:31"	"pocet smazanych radku je: 2"
"16-10-2019 23:00:31"	"pocet smazanych radku je: 3"
"16-10-2019 22:00:31"	"pocet smazanych radku je: 2"
"16-10-2019 21:00:31"	"pocet smazanych radku je: 5"
"16-10-2019 20:00:31"	"pocet smazanych radku je: 8"
"16-10-2019 19:00:31"	"pocet smazanych radku je: 3"
"16-10-2019 18:00:31"	"pocet smazanych radku je: 8"

**Comment by romanstrobl** [comment]
I plan to look at this issue during next week.

**Comment by romanstrobl** [comment]
@radekfrolik For your information, I have just released version `0.23.0`, which includes a fix for this bug.
