### ISSUE TITLE
Proxy authentication support for FCM

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-push-server#269]
`GoogleCredential` class uses OAuth 2.0 protocol  to obtain access tokens, however the default Google HTTP client based on java.net HTTP client does not support proxy authentication:

https://github.com/googleapis/google-http-java-client/issues/190

We can workaround this issue by using the `java.net.Authenticator` for release `0.22.x`, given that the Google `NetHttpTransport` class does not allow setting proxy authentication. This cannot be considered a proper solution though, just a workaround of missing functionality in Google HTTP client library.

To fix the issue properly in the future we can consider switching to `google-http-client-apache-v2` which should support Proxy authentication.

**Comment by pmagam-tibco** [comment]
Can you please let me which google-http-client version supports Proxy authentication?I downloaded  google-http-client 1.34.2,1.41.8.But I don't see setProxyAuthentication() or any methods being added to add proxy server credentials.Please help.

**Comment by petrdvorak** [comment]
@pmagam-tibco This is not a support thread for `google-http-client`, ask there or see how we fixed the issue in PR #279.
