### ISSUE TITLE
Remove push client instance from server

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-push-server#314]
We still have:

```java
    @Bean
    public PushServerClient pushServerClient() {
        return new PushServerClient(pushServiceUrl);
    }
```

... in [the source codes](https://github.com/wultra/powerauth-push-server/blob/develop/powerauth-push-server/src/main/java/io/getlime/push/configuration/PowerAuthWebServiceConfiguration.java#L69). Is it still needed?

**Comment by romanstrobl** [comment]
The client is used in the tests. We can move it into the test sources though.

**Comment by romanstrobl** [comment]
The client is used in the tests. We can move it into the test sources though.
