### ISSUE TITLE
Add GeoTrust to Pushy client

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-push-server#381]
See the following issues for details:

- https://github.com/jchambers/pushy/issues/809
- https://github.com/jchambers/pushy/issues/833

The new Java version does not contain a GeoTrust certificate and hence calls fail on SSL handshake.

**Comment by romanstrobl** [comment]
It seems that the Pushy library is not yet released with a fix of this issue. I suggest for now that we add a comment to release notes that Java 8 or 11 is supported and there is an issue with connecting to APNs on Java 14 due to missing certificate.

**Comment by petrdvorak** [comment]
You can still add the certificate, I will have a look... https://pushy-apns.org/apidocs/0.14/com/eatthepath/pushy/apns/ApnsClientBuilder.html#setTrustedServerCertificateChain(java.io.File)

**Comment by petrdvorak** [comment]
@romanstrobl Let's release this version without it, though...
