### ISSUE TITLE
Add support for asynchronous requests

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-push-server#462]
Sometimes, the client may not care about the response details we provide. To allow faster synchronous processing on client side, we should allow asynchronous messages.

- The client would add `"mode": "asynchronous"` to the request (default would be `"mode": "synchronous"`).
- The server would return a mode in the response and if the mode is `asynchronous`, there would be no details of sent messages.

**Comment by romanstrobl** [comment]
We should probably use: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202
