### ISSUE TITLE
Null values in extras cause a problem to APNS

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-push-server#675]
If extras map contains null values, APNS does not send the payload. It is s known Apple issue https://developer.apple.com/forums/thread/727395

**Comment by zcgandcomp** [comment]
@banterCZ check the how to test.

**Comment by banterCZ** [comment]
How to test:

Send a message with any key with a null value in extras. Before the fix, the push notification was not sent to Apple. https://developers.wultra.com/components/powerauth-push-server/1.5.x/documentation/Push-Server-API#post-pushmessagesend

**Comment by kopovan** [comment]
Also tested alternative scenarios:
1. "silent" parameter set to false - the push notification was not sent
2. sending the message to a non existing userId/registrationId - the notif. was not sent
```
{
  "status": "OK",
  "responseObject": {
    "mode": "SYNCHRONOUS",
    "ios": {
      "sent": 0,
      "failed": 0,
      "pending": 0,
      "total": 0
    },
    "android": {
      "sent": 0,
      "failed": 0,
      "pending": 0,
      "total": 0
    }
  }
}
```
3. Double checked the JSON parsing - all works as expected
4. Long title and body
<img src="https://github.com/wultra/powerauth-push-server/assets/135111051/9614f39a-6c76-4e8b-af17-09185aca94ff" width="300" />

5. Valid until?
