### ISSUE TITLE
Add warning when push notification cannot be sent due to an invalid userId or userId+activationId combination

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-push-server#841]
Currently if `userId` or combination of `userId` and `activationId` doesn't have any activation to send push notification to, we do not send the push, but push server doesn't provide any warning.

Add to log WARN message that no device was found to send the push notification to.

(Alternatively we can raise an exception if the combination is not valid - TBD)

**Comment by banterCZ** [comment]
Let's rather throw an exception.
