### ISSUE TITLE
Push messages sent via FCM to APNs are not constructed correctly

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-push-server#913]
We should update the payload of push messages which are sent via FCM to APNs, so that all push message parameters for APNs are mapped correctly including silentness of the push message, title, body, extras, sound, and other parameters which can be controlled using Push Server REST API.

**Comment by romanstrobl** [comment]
Testing considerations:
- Push messages are delivered to APNs successfully via FCM.
- Push message silentness is handled correctly.
- Following parameters can be set and work well with updated mobile SDK:
  - title, including localization
  - body, including localization
  - sound
  - category name
  - badge number
  - content-available (silent push or not)
  - thread ID (collapse key)
  - custom properties (extras)
  - priority

**Comment by kopovan** [comment]
all tests done within https://github.com/wultra/tasklist/issues/393#issuecomment-2549071879
