### ISSUE TITLE
Creating device registration in multi-user mobile app setup overwrites the previous registration

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-push-server#923]
## Use case scenario

- PowerAuth-based app that allows multiple users (multiple powerauth activations - imagine Instagram or Facebook multiple account setup)
- User 1 enrolls the device to his account (creates PowerAuth activation)
- User 1 registers for the push notifications
- User 2 enrolls the same device to his account (creates PowerAuth activation)
- User 2 registers for the push notifications
- Now only user 2 is able to receive notifications
- When user 1 registers again, only user 1 is able to receive push notifications
- etc...

## What is the problem

The problem is that when seconds activation is registered with the same push token (push token is the same for the application) as another already created record in the database, the same row is reused, even if the activationId is different.

```
# user 1 registered
1604  "e350450e-3fac-420d-b0f5-df9a43fe8666"  "koberpushtest1"  1 "ios" "D393968A5D41EECA112D348D0D34888D6AC6F84C04290347FBA3EA470852109E"  "2024-12-11 13:07:14.287" true  "development"
# User 2 registered (the same row with the ID 1604 is reused making the previous activation unable to receive notifications)
1604  "2ffb43a0-8044-4c37-8f01-c3b69889e2f0"  "koberpushtest2"  1 "ios" "D393968A5D41EECA112D348D0D34888D6AC6F84C04290347FBA3EA470852109E"  "2024-12-11 13:08:56.299" true  "development"
```

## The code

The issue is happening here, when a device is registering for push, a lookup is made:
https://github.com/wultra/powerauth-push-server/blob/develop/powerauth-push-server/src/main/java/io/getlime/push/service/DeviceRegistrationService.java#L71C60-L71C85

The lookup returns a single result (because it's matched by the push token) from here:
https://github.com/wultra/powerauth-push-server/blob/develop/powerauth-push-server/src/main/java/io/getlime/push/service/DeviceRegistrationService.java#L207

This single record is then updated making the original activation unable to receive notifications:
https://github.com/wultra/powerauth-push-server/blob/develop/powerauth-push-server/src/main/java/io/getlime/push/service/DeviceRegistrationService.java#L78

**Comment by zcgandcomp** [comment]
@zcgandcomp agrees with the product on the proper solution.

**Comment by zcgandcomp** [comment]
New solution will be specified
