### ISSUE TITLE
Platform upgrade is ignored

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-push-server#924]
## Use case scenario

- App is using old SDK and sending IOS 
- App is upgraded to new SDK and starts sending APNS
- Platform in the table is not upgraded - still IOS until manually deleted from the database

This is a much bigger problem if the upgrade was made from IOS to FCM, then the push would stopped working and never started working again for this activation

**Comment by kopovan** [comment]
retest ok

![Image](https://github.com/user-attachments/assets/fe0b6712-6c9c-4fd5-b3dc-b3bdef5ff0bb)

![Image](https://github.com/user-attachments/assets/1648836e-c54b-498d-b6a3-0613567cb746)
