### ISSUE TITLE
timestamp_last_registered is not updated in push_device_registration table

### ISSUE THREAD

**Issue by kopovan** [wultra/powerauth-push-server#931]
The issue occurs on multiple builds - new sdk and old sdk, as well as on new BE and old BE

1. 
Android: Wultra Key - DEV app, version 12.0.0DEV (693) - New SDK
BE: Old DEV env. (New BE) and OneID env. (Old BE) - the issue occurs in both env.

2.
Android: Wultra Key - DEV app, version 12.0.0DEV (695) - Old SDK
BE: Old DEV env. (New BE)

Point of the test: verify that the `timestamp_last_registered` column in the `push_device_registration` table is updated when the app is reopened.

1. register user in the app
2. new record is created
3. close the app and reopen
Expected result: `timestamp_last_registered` is updated
Actual result: `timestamp_last_registered` remains the same

![Image](https://github.com/user-attachments/assets/75ca0342-878c-4188-b8a8-bfa2c63f769e)

![Image](https://github.com/user-attachments/assets/55f48047-4b37-4642-8a9d-2845560eb7d1)

**Comment by romanstrobl** [comment]
@kober32 I check the backend code and do not see a reason why the `timestamp_last_registered` would not be updated during device registration. Can you check whether the SDK always sends a registration request when the mobile application is reopened?

**Comment by kopovan** [comment]
This behaviour is expected on Android, confirmed with Kober. I am closing this issue as it is not a bug.
